# Generated by Django 6.0 on 2025-12-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("author", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "cover",
                    models.CharField(
                        choices=[("hard", "Hard cover"), ("soft", "Soft cover")],
                        default="soft",
                        max_length=10,
                    ),
                ),
                ("inventory", models.PositiveIntegerField()),
                (
                    "daily_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
                "ordering": ["title", "author"],
            },
        ),
    ]
