# Generated by Django 6.0 on 2025-12-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="inventory",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
