# Generated by Django 6.0 on 2025-12-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowing",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("returned", "Returned"),
                    ("overdue", "Overdue"),
                ],
                default="active",
                max_length=10,
            ),
        ),
    ]
